spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
#  profiles:
#    active: production

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

#  thymeleaf:
#    prefix: classpath:/static/
#
#  mvc:
#    view:
#      suffix: .html
#
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      use-sql-comments: true
    database-platform: org.hibernate.dialect.H2Dialect


#server:
#  servlet:
#    encoding:
#      charset: UTF-8
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace
